import './js/preloader';
import './js/render-gallery';
import './js/team-modal';
import './js/pagination';
import './js/loading';
import './js/api-service';
import './js/modal';
import './js/search-film';
import './js/authentication/authentication';
